# Railway Configuração
version: 2

build:
  builder: NIXPACKS

deploy:
  restartPolicyType: ON_FAILURE
  restartPolicyMaxRetries: 10

variables:
  NODE_ENV: production
  PORT: 3000

healthcheck:
  httpPath: /
  httpPort: 3000